target ‘H/Users/love/iOSProject/iOSProject/Pods/Pods.xcodeprojHExtend’ do
platform :ios, ‘8.0’

inhibit_all_warnings!


pod 'Masonry'
pod 'SDWebImage'
pod 'AFNetworking'
pod 'MJRefresh'
pod 'MJExtension'
pod 'IQKeyboardManager'
pod 'SSKeychain'
pod 'UMengAnalytics-NO-IDFA'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'DZNEmptyDataSet'
# 二维码
pod 'HMQRCodeScanner'
end
